### PR TITLE
Java 7 and code readability

### PR DESCRIPTION
**Pull request by albuhuba**
The code quality/readability is now enhanced a little bit. I would like
to use this tool therefore I would like to contribute to make it better.
Are you interested in a collaboration?

### CODE REVIEW

**Comment by jmrozanec** [comment]
@albuhuba thank you for the pull request. You are most welcome to contribute to this project! Thanks!

**Comment by jmrozanec** [comment]
@albuhuba merged!

**Comment by albuhuba** [comment]
@jmrozanec Are you using any special custom and common formatter for the project? I am using Eclipse Neon for source code editing.

**Comment by jmrozanec** [comment]
@albuhuba we are not using any formatter for the project. I would not like to enforce it also, to keep setup requirements at minimum for any contributor. Enforcing it via Maven it is possible (there are some plugins that would format the code when building, so that everyone get the same code independently if the IDE we use), but may format in detriment of the expressiveness you give when indenting code in a certain way. How do you see this? Ideas and contributions are always welcome.

**Comment by albuhuba** [comment]
@jmrozanec Thanks for the update, usually I do like order, therefore I would prefer the possibility to have a common formatter and cleanup for the different IDE's, but this should be just a guideline instead of enforcement.

**Pull request merged**
