### PR TITLE
#285 fix sonarqube issues

### PR DESCRIPTION
**Pull request by Naxos84**
Removed deprecated constructors of Always and QuestionMark in Test Files.
Added sonarcloud badge to readme.
Removed vulnerabilities.
Removed issues in non-test classes.

### CODE REVIEW

**Comment by Naxos84** [comment]
codacy is failing because I touched a lot of classes/methods without being able to fix all checkstyle issues that were present previously.

**Comment by jmrozanec** [comment]
@Naxos84 Thank you for working on this! Will review tonight and merge. Thanks!

**Comment by Naxos84** [comment]
@jmrozanec there is more to come. :-)

Am 29.11.2017 15:16 schrieb "jmrozanec" <notifications@github.com>:

**Comment by jmrozanec** [comment]
@Naxos84 glad to hear that!

**Pull request merged**
