### PR TITLE
General code cleanup

### PR DESCRIPTION
**Pull request by albuhuba**
* readability improvements
* unused code removal
* extracting constants, uniformization still needed
* potential NPE verification
* eliminating contains on list -> double getNode on HashMap reduced to 1
* diamond operator where observed

### CODE REVIEW

**Comment by jmrozanec** [comment]
@albuhuba thanks for the patches! May I ask you to use Unix style line endings when committing? If you are using git-bash on windows, there is a configuration to push files always using unix line endings. I would appreciate if you can do that before merging your PR. Thanks!

**Comment by albuhuba** [comment]
I've changed the line break and commited the changes again. Do I have to do anything else?

**Comment by jmrozanec** [comment]
@albuhuba I had no time to review it again - will do so tomorrow evening. In the original PR I saw you removed some constructors as well as a Factory. Those are required, not directly in the cron-utils project, but to provide functionality to users (there are some usage examples available at [cron-utils-examples](https://github.com/jmrozanec/cron-utils-examples) ). Thanks!

**Comment by jmrozanec** [comment]
@albuhuba thank you for the patch - now is merged. Some observations on the code you submitted:
- we use constructors like And(And) in order to create copies of the element where required. Works like a "clone". There was a useful case related to a visitor, that required accessing them in some point.
- FieldExpressionFactory was deleted, but being used: not in the project, but provided to clients. A demo code is available at [cron-utils-examples](https://github.com/jmrozanec/cron-utils-examples).
- [EMPTY_STRING is usually a bit longer to write than just "" ](http://stackoverflow.com/questions/3450604/why-is-there-no-string-empty-in-java). We would like to favour "". In the case of EMPTY_STRING, we accept the constant, just to avoid mistakes typing two or more spaces.
Thanks!

**Comment by albuhuba** [comment]
Good morning/day,

@jmrozanec Thanks for the heads up, regarding the empty string and constants, I am always having in mind to have a common place where all the related constants are defined which are widely used. At this point I've considered they are good to be extracted and then with one major effort they can be centralized.
I wasn't aware that the FieldExpressionFactory was used by clients, just it didn't seemed correct to have something in an utility where it is not used. One could argue that this is good or not and I've got to the conclusion even if it's used, it is not the proper place to exist.

I am doing these little changes, but they are open for discussion. We can always get to a common ground with the style of code and habits but most probably it will take some time.

**Comment by jmrozanec** [comment]
@albuhuba sure. That's why the feedback :) Thanks for contributing!

**Pull request merged**
