### PR TITLE
Fix IllegalArgumentException when trying to parse `@monthly` nickname

### LINKED ISSUE #522: IllegalArgumentException when trying to parse `@monthly` nickname
# Bug description
When trying to parse cron expression `@monthly` using the Cron parser the following exception occurs:
```
Caused by: java.lang.IllegalArgumentException: Cron expression contains 1 parts but we expect one of [5]
	at com.cronutils.parser.CronParser.parse(CronParser.java:150)
	at org.betonquest.betonquest.api.schedule.CronSchedule.<init>(CronSchedule.java:93)
	... 71 more
```

The following Cron definition was used:
```java
    /**
     * The unix cron syntax with support for nicknames
     */
    public static final CronDefinition DEFAULT_CRON_DEFINITION = CronDefinitionBuilder.defineCron()
            .withMinutes().withValidRange(0, 59).withStrictRange().and()
            .withHours().withValidRange(0, 23).withStrictRange().and()
            .withDayOfMonth().withValidRange(1, 31).withStrictRange().and()
            .withMonth().withValidRange(1, 12).withStrictRange().and()
            .withDayOfWeek().withValidRange(0, 7).withMondayDoWValue(1).withIntMapping(7, 0).withStrictRange().and()
            .withSupportedNicknameYearly().withSupportedNicknameAnnually()
            .withSupportedNicknameMonthly().withSupportedNicknameWeekly()
            .withSupportedNicknameMidnight().withSupportedNicknameDaily()
            .withSupportedNicknameHourly()
            .instance();
```
And the following code can be used to reproduce it:
```java
new CronParser(DEFAULT_CRON_DEFINITION ).parse("@monthly");
```

## Expected Behaviour
The parser should correctly parse `@monthly`, throwing no exceptions and returning the same cron as defined by `0 0 1 * *`.

-----------
_I'll look into creating a pull request with unit tests and a fix_

### PR DESCRIPTION
**Pull request by J0B10**
Fixes #522

### CODE REVIEW

**Review by Wolf2323 — APPROVED** [review]
I am from the same project as J0B10 so i had a look on that and i think LGTM.

**Comment by jmrozanec** [comment]
@J0B10 @Wolf2323 merged! Thanks! 😄

**Comment by jmrozanec** [comment]
@J0B10 @Wolf2323  release 9.1.7 was published with this fix.

**Comment by J0B10** [comment]
Thanks for letting us know! 

Now we no longer need to rely on a jitpack snapshot. :+1:

**Comment by jmrozanec** [comment]
@J0B10 glad to hear! 😄 🚀

**Pull request merged**
