### PR TITLE
4.x.y

### PR DESCRIPTION
**Pull request by fante76**
I've added Italian missing properties. You should add for other language not english too, otherwise software give error on locale!=en.

[CronUtilsI18N_it.properties.txt](https://github.com/jmrozanec/cron-utils/files/570850/CronUtilsI18N_it.properties.txt)

### CODE REVIEW

**Comment by jmrozanec** [comment]
@fante76 Great! Thank you for contributing. Will check soon and merge to brach 4.x.y and master.
Please disgregard the failed build at the PR - is not configured to deploy versions at PR branches, and thus the builds fail.

**Comment by jmrozanec** [comment]
@fante76 please note that branches 4.x.y and master are not compatible. I will merge this into 4.x.y and cherrypick to master.

**Comment by fante76** [comment]
Ok
Sorry for my mistake, but I've done all on work time and in few minutes.

Thank you

Il 04/nov/2016 20:06, "jmrozanec" <notifications@github.com> ha scritto:

**Comment by jmrozanec** [comment]
@fante76 Sure! Not a problem :) Thank you for contributing!

**Comment by jmrozanec** [comment]
@fante76 just released versions 4.1.3 and 5.0.4 with all keys for Italian locale. Thanks!

**Comment by fante76** [comment]
In version 5.0.5 Italian labels are incomplete...
This is the labels I use in my project

```
between_x_and_y=tra {0} e {1}
every=ogni
and=e
at=al
day=giorno
days=giorni
hour=ora
hours=ore
minute=minuto
minutes=minuti
second=secondo
seconds=secondi
month=mese
months=mesi
year=anno
years=anni
between=tra
of_every_month=di ogni mese
of_the_month=del mese
last=ultimo
the_nearest_weekday_to_the=il giorno della settimana più vicino a
last_day_of_month=ultimo giorno del mese
last_weekday_of_month=ultimo giorno della settimana nel mese
```

**Comment by jmrozanec** [comment]
@fante76 Please note [those same properties were pushed for 5.x.y](https://github.com/jmrozanec/cron-utils/blob/master/src/main/resources/CronUtilsI18N_it.properties)

**Comment by fante76** [comment]
Sorry... my problem with maven.

**Comment by jmrozanec** [comment]
@fante76 No problem :)

**Pull request closed without merging**
