### PR TITLE
Revise improved handling of optional cron expression fields

### PR DESCRIPTION
**Pull request by meincs**
added cleanups, i.e. removed unused imports

### CODE REVIEW

**Comment by jmrozanec** [comment]
@meincs thank you for the contributed pull request. This is a great feature. We see value in the implemented DAY_OF_YEAR idea and will be glad to keep it. On the other side, FieldExpressions class was modified such that any field can be rendered optional. Since only information available at a cron expression is the position, the only optional field can be the last one. Is there some validation in place to enforce such a behavior when building the expression? Thanks!

**Comment by meincs** [comment]
I've already added some validation in place. Have a look at CronDefinitionBuilder#register(FieldDefinition). Now it is possible to define cron definitions that have more than one optional field. However, in a concrete instance it is not possible to skip opttional fields. For example given the Quartz Cron definition thta is extended by a DAY_OF_YEAR field, the YEAR filed has to be defined for expressions that specify a DAY_OF_YEAR value.

**Comment by jmrozanec** [comment]
@meincs great! We will check today and eventually come back with some more questions. Thanks!

**Comment by meincs** [comment]
@jmrozanec great! I'm looking forward to your decision or questions.

**Comment by jmrozanec** [comment]
@meincs this pull request was great! Thank you for contributing the feature and in such a neat way. :smile: We really look forward to future collaborations!

**Pull request merged**
