### PR TITLE
adding test representing failure of nextExecution() on Issue #228

### PR DESCRIPTION
**Pull request by kensipe**
Issue #228 has more examples of failures but these test probably cover what is needed.

### CODE REVIEW

**Comment by jmrozanec** [comment]
@kensipe Many thanks for the PR and for reporting the issue! We will try to solve ASAP. Help is always welcome! 😄

**Comment by kensipe** [comment]
@jmrozanec yeah... I'm hoping to get some time to work on this...

**Comment by jmrozanec** [comment]
@kensipe Working during October [can be rewarding](hacktoberfest.digitalocean.com/#projects) ;)

**Comment by kensipe** [comment]
@jmrozanec I would want to align with Java 8 dates... LocalDateTime, etc.  any issues with that?

**Comment by jmrozanec** [comment]
@kensipe we are managing to keep compatibility with Java 7, since Android does not fully support JDK8 yet.

**Pull request merged**
