### PR TITLE
474

### PR DESCRIPTION
**Pull request by albertotn**
I've followed this steps while working on #474 :

- update my fork
- clone the repository
- install java 16 ( from https://adoptopenjdk.net/ )
- installed last release of eclipse: 2021-09 (4.21.0)
- change version of java from 1.8 to 16
- fixed a test not working in my locale
- removed one unused import

All test are passed, so I think cron-utils is ready for Java 16, there are some other test I need to do ?

### CODE REVIEW

**Comment by jmrozanec** [comment]
@albertotn should be ok 😄 Thanks! We just merged!

**Comment by albertotn** [comment]
Great! Can you label this PR to hacktoberfest-accepted ?

**Comment by jmrozanec** [comment]
@albertotn done!

**Comment by albertotn** [comment]
Thanks, if you want open a new issue for java 17 and assign to me, os I will check asap too

**Comment by jmrozanec** [comment]
@albertotn deal 😄 Here the new issue: https://github.com/jmrozanec/cron-utils/issues/486

**Pull request merged**
