### PR TITLE
Remove unused java.util.stream.Collectors import

### PR DESCRIPTION
**Pull request by jaredculp**
This is preventing running under JDK7.

### CODE REVIEW

**Comment by jaredculp** [comment]
@jmrozanec please review when you get a chance :)

**Comment by jmrozanec** [comment]
@jaredculp done! Thanks! 😄

**Comment by jaredculp** [comment]
Wow thanks for the quick review! Any chance a release can be cut so my java7 project can depend on this lib?

**Comment by jmrozanec** [comment]
@jaredculp let me review this tonight, and check requirements for an Android release. Will come back then, with a schedule.

**Pull request merged**
