### PR TITLE
fix ArrayIndexOutOfBoundsException when parsing incomplete steps expr.

### PR DESCRIPTION
**Pull request by francisdb**
eg: `*/ * * * * ?`

### CODE REVIEW

**Comment by francisdb** [comment]
Failing build is unrelated to pr (snapshot deploy fails)

**Comment by jmrozanec** [comment]
@francisdb Thank you for contributing a fix and related test! The pull request was merged!

**Comment by francisdb** [comment]
@jmrozanec great, now all I need is a release ;-)

**Comment by jmrozanec** [comment]
@francisdb sure! Tonight I will release a new version with this fix!

**Comment by jmrozanec** [comment]
@francisdb [New version](https://github.com/jmrozanec/cron-utils/releases/tag/3.1.5) was released! My apologies for the delay.

**Pull request merged**
