### PR TITLE
use Collections sort method for android branch

### PR DESCRIPTION
**Pull request by tylergets**
I am submitting this PR for more help as I am having trouble getting the package to compile on jitpack, so testing is a bit difficult. 

This PR attempts to fix issue #309 on android versions 6.0.1 and less.

Its meant only for the 6.0.x branch

### CODE REVIEW

**Comment by L4grange** [comment]
Awesome! I'll test it out once I get the time, for now I use my own subclass of CronParser with a fix in place, would be great to see this fixed on the repo!

**Comment by jmrozanec** [comment]
@tylergets thanks! Will merge this soon! 😄

**Comment by tylergets** [comment]
@jmrozanec @L4grange any updates on this PR? Looking to get it into our app :)

**Comment by jmrozanec** [comment]
@tylergets today we are merging it and releasing a new version. We apologize for the delay. Best!

**Comment by jmrozanec** [comment]
@tylergets version 6.0.6 was released with this fix! We are closing the PR. Thank you for contributing to cron-utils!

**Pull request closed without merging**
