### PR TITLE
Simplify next potential time calculation

### PR DESCRIPTION
**Pull request by pkoenig10**
Follow up to #351

To hopefully avoid issues similar to #319 when computing next potential times.

### CODE REVIEW

**Comment by jmrozanec** [comment]
@pkoenig10 merged! Thanks!

**Comment by pkoenig10** [comment]
@jmrozanec would it be possible to get a release with the fix for #319?

**Comment by jmrozanec** [comment]
@pkoenig10 sure! In about 6hs will be ok? Best!

**Comment by jmrozanec** [comment]
@pkoenig10 released! Thank you for contributing to cron-utils! :smile:

**Pull request merged**
