### PR TITLE
Issue #343

### PR DESCRIPTION
**Pull request by minidmnv**
Change DoW and DoM constraint to work as it should. Add test, and improve two of them.

### CODE REVIEW

**Comment by jmrozanec** [comment]
@minidmnv thank you for watching this case. Reviewing the code, may be that with the new version we ensure DoM='?' enforces that DoW will never be '?', but not the other way around? We may need to enforce the other case as well. Thanks!

**Comment by minidmnv** [comment]
@jmrozanec I could check it in other way too, but in my opinion it will be redundand. We have to ensure that DoW, neither DoM equals question mark. I think, that when we have positive match on DoM (it's different to question mark) we don't have to check day of week at all.

Ive also added two test for this cases.

What You think about that?

**Comment by jmrozanec** [comment]
@minidmnv thank you for the explanations and the additional tests. I see the following scenarios, assuming a QUARTZ definition, which requires us to set or DoW or DoM, but not both or not both '?'. The 'Validated?' checks conditions considered in the PR. Notice that an invalid scenario arises, which corresponds to some tests on which you modified the expected outcome by removing expected exceptions. We are rejecting the PR by now.

|#|s|M|H|DoW|M|DoM|Y|Valid?|Validated?|
|-|-|---|--|-------|--|-------|--|------------|--------------|
|1|*|*|*|*|*|*|*|NO|NO|
|2|*|*|*|?|*|*|*|YES|NO|
|3|*|*|*|*|*|?|*|YES|YES|

**Comment by minidmnv** [comment]
Okay, my mistake, I've overlook that one detail, that both fields can't be set as well, as not. I'll amend this today. Sorry for misunderstanding.

**Comment by jmrozanec** [comment]
@minidmnv do we have any news on this? We would like to merge the PR, but the last fix is missing ...

**Comment by jmrozanec** [comment]
@minidmnv do we have any update on this? Otherwise we will close the PR. Thanks!

**Comment by jmrozanec** [comment]
@minidmnv we are closing the PR due to lack of response. Please feel free to re-open on any update on this issue! Thanks! 😄

**Pull request closed without merging**
