### PR TITLE
Add test for issue #477

### PR DESCRIPTION
**Pull request by arunvelsriram**
Added test for #477

### CODE REVIEW

**Comment by jmrozanec** [comment]
@arunvelsriram thanks! 😄

**Comment by arunvelsriram** [comment]
@jmrozanec am new to this repo. we have closed the issue already and this PR is merged. How do we track this issue till its fixed?

**Comment by jmrozanec** [comment]
@arunvelsriram will be tracked on [this issue](https://github.com/jmrozanec/cron-utils/issues/477) Please feel free to help us develop a fix for it. Best!

**Comment by arunvelsriram** [comment]
@jmrozanec Sure. Sorry I thought the issue was closed. Thanks for clarifying :)

**Pull request merged**
