### PR TITLE
Refactor joda to java8

### PR DESCRIPTION
**Pull request by espiegel**
Removed joda-time dependency. Added a joda-time exclusion from `htime`.

Replaced instances of Joda's `DateTime` with Java 8's `ZonedDateTime`.

All tests pass.

### CODE REVIEW

**Comment by espiegel** [comment]
How come the travis-ci build is failing? Its giving this error:

```
The command "mvn deploy --settings target/travis/settings.xml -Dsettings.security=target/travis/settings-security.xml" exited with 1.
```

**Comment by jmrozanec** [comment]
@espiegel We expect that failures, since has no security configurations to push a SNAPSHOT to Maven central for each build, as the master branch has, and I did not create a separate build for PRs.
Just checked your changes, and merged. Thank you for contributing! Will soon release a version with this major change!

**Comment by espiegel** [comment]
@jmrozanec Awesome. Let me know when then major version is released, I need this for another project :)

**Comment by jmrozanec** [comment]
@espiegel released! Thank you again! 
If the project you are working on can be showcased as a cron-utils use case, you are welcome to share some link or sample on how you found it useful.

**Pull request merged**
